[placeholders.description]
type = "string"
prompt = "What is the description of your cli tool?"

[template]
ignore = [
  ".github/dependabot.yml",
  ".github/workflows/",
]

[hooks]
post = ["pre.rhai"]