name: test

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-make
          version: latest
          use-tool-cache: true
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-generate
          version: latest
          use-tool-cache: true
      - uses: actions/checkout@v3
      - name: Run tests
        run: ./test-template.sh
