name: test

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    cron: '0 0 * * 5'

jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: test-project
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - uses: cargo-generate/cargo-generate-action@v0.11.0
        with:
          name: ${{ env.PROJECT_NAME }}
          other: "--define description=Bar"
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-make
          version: latest
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-outdated
          version: latest
      - name: Test template
        run: |
          set -e 

          mv $PROJECT_NAME ${{ runner.temp }}/
          cd ${{ runner.temp }}/$PROJECT_NAME

          cargo make check-format
          cargo make clippy
          cargo make test
          cargo outdated --exit-code 1
